language: go
go:
  - 1.8.x
# https://docs.travis-ci.com/user/database-setup/#MongoDB
services: mongodb
install:
  - go get -t ./...
script: GOMAXPROCS=4 GORACE="halt_on_error=1" go test -race -v ./...
